$axure.loadCurrentPage({
  "url":"首页.html",
  "generationDate":new Date(1417419974061.82),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"8a62e2c292b04564964a92a9c3fd5166",
    "type":"Axure:Page",
    "name":"首页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFF333333},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"91fd257011b144dab649173af1b4d7fd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":100,
              "y":100},
            "size":{
              "width":332,
              "height":339}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66fbcd6b61f744989ea42650d85c9213",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":100,
                  "y":100},
                "size":{
                  "width":332,
                  "height":339}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u0.png"}},
{
          "id":"6d0499fc00b647bab82f19d04e7d0a87",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "fill":{
              "fillType":"solid",
              "color":0x660033FF},
            "location":{
              "x":114,
              "y":403},
            "size":{
              "width":90,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7434774c8914411c8c426cf241aa396c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "fill":{
                  "fillType":"solid",
                  "color":0x660033FF},
                "location":{
                  "x":114,
                  "y":403},
                "size":{
                  "width":90,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u2.png"}},
{
          "id":"480f6403d6734dd7bc32b199f924700b",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":154,
              "y":420},
            "size":{
              "width":10,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/首页/u4_end.png",
            "line~":"images/首页/u4_line.png"}},
{
          "id":"45541f2ef2c540e28bb775f7e9408b29",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":114,
              "y":500},
            "size":{
              "width":149,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c507794c7a74f12832fe93fd59eec1f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":114,
                  "y":500},
                "size":{
                  "width":149,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u5.png"}},
{
          "id":"459dc461c4f04c958221129332a5e3c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":264,
              "y":500},
            "size":{
              "width":149,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d80242d9f24045f7912b2fa226aab1ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":264,
                  "y":500},
                "size":{
                  "width":149,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u5.png"}},
{
          "id":"4ea404f8391c47c3b229c369ced823cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":224,
              "y":507},
            "size":{
              "width":28,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a1e9f2a67e16403fb87b8be4d48bdad8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":224,
                  "y":507},
                "size":{
                  "width":28,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u9.png"}},
{
          "id":"abed30765e3f4277a56db72d03581173",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":124,
              "y":506},
            "size":{
              "width":109,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d96607f28ae4018811fcd4d5556d289",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":124,
                  "y":506},
                "size":{
                  "width":109,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6063f49ec90448288a89056868fd7e4b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":372,
              "y":507},
            "size":{
              "width":30,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca29fffc5df64bd381b23b8fa7d5bae3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":372,
                  "y":507},
                "size":{
                  "width":30,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u13.png"}},
{
          "id":"e213347119534a5a93efc79cfed03d45",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":276,
              "y":506},
            "size":{
              "width":109,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a1b4b62e1bc49ca88b4b2250d5b7e4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":276,
                  "y":506},
                "size":{
                  "width":109,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"03af1254e706447e8185b05be2795222",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"10px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":122,
              "y":526},
            "size":{
              "width":68,
              "height":17},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777},
            "cornerRadiusTopLeft":"15"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5140c360fc8f4c10bd9623698020e03e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"10px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":122,
                  "y":526},
                "size":{
                  "width":68,
                  "height":17},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF777777},
                "cornerRadiusTopLeft":"15"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u17.png"}},
{
          "id":"806854db1b2f40ca90bcd4396722638d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"10px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":273,
              "y":526},
            "size":{
              "width":68,
              "height":17},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777},
            "cornerRadiusTopLeft":"15"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cbb60be409584f67a2ace45720c50e74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"10px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":273,
                  "y":526},
                "size":{
                  "width":68,
                  "height":17},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF777777},
                "cornerRadiusTopLeft":"15"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u17.png"}},
{
          "id":"6d6bdb49d5604fff86f82597c1281b37",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "fill":{
              "fillType":"solid",
              "color":0x660033FF},
            "location":{
              "x":273,
              "y":403},
            "size":{
              "width":90,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51c3453d7fca4a8e83e01c1ab94bd24c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "fill":{
                  "fillType":"solid",
                  "color":0x660033FF},
                "location":{
                  "x":273,
                  "y":403},
                "size":{
                  "width":90,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u2.png"}},
{
          "id":"c61efe91906646618540b537919dd2b4",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":313,
              "y":420},
            "size":{
              "width":10,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/首页/u4_end.png",
            "line~":"images/首页/u4_line.png"}},
{
          "id":"b223fa457ffe4e78b9ed449e9aa9da6c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "fill":{
              "fillType":"solid",
              "color":0x660033FF},
            "location":{
              "x":390,
              "y":130},
            "size":{
              "width":42,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc6279f579ff41f6b16838efdd3014c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "fill":{
                  "fillType":"solid",
                  "color":0x660033FF},
                "location":{
                  "x":390,
                  "y":130},
                "size":{
                  "width":42,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u24.png"}},
{
          "id":"baae714d05ec4575be3ade8626c1ef63",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":420,
              "y":140},
            "size":{
              "width":200,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/专题列表/u66_end.png",
            "line~":"images/首页/u26_line.png"}},
{
          "id":"9b5a14a320d344949e09c0b4bf12f489",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":450,
              "y":80},
            "size":{
              "width":391,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf86bc64d4724386847a745628267ac7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":450,
                  "y":80},
                "size":{
                  "width":391,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u27.png"}},
{
          "id":"20f521266fb44f12bc6e179e8e6d4aee",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":450,
              "y":160},
            "size":{
              "width":391,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be442ada4b9a44b2a73a5f9ebef6dfc9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":450,
                  "y":160},
                "size":{
                  "width":391,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u29.png"}},
{
          "id":"e13ac42e461a4f8b8600341f4e54dc78",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":684,
              "y":54},
            "size":{
              "width":157,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a4507598b594b768a5f1abf286ee9f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":684,
                  "y":54},
                "size":{
                  "width":157,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cf70fdd5496744d88ec3d2b4b65d723b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":460,
              "y":232},
            "size":{
              "width":107,
              "height":75}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6954997fe60c4b488efe87ab8e04f62a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":460,
                  "y":232},
                "size":{
                  "width":107,
                  "height":75}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u33.png"}},
{
          "id":"e04eba76cbe44f33b26c68275083af48",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":620,
              "y":232},
            "size":{
              "width":107,
              "height":75}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09ba5457370e46fab12d6fcb3301f65d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":620,
                  "y":232},
                "size":{
                  "width":107,
                  "height":75}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u33.png"}},
{
          "id":"e44e4888cf1547ddbfb92460a0b990f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "fill":{
              "fillType":"solid",
              "color":0xFFFF4040},
            "location":{
              "x":660,
              "y":280},
            "size":{
              "width":52,
              "height":27},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3632370b358a47f88d15eedbc029d9a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF4040},
                "location":{
                  "x":660,
                  "y":280},
                "size":{
                  "width":52,
                  "height":27},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u37.png"}},
{
          "id":"f7033c065cbd42d6aabdcfe5f5bf1cb6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":670,
              "y":286},
            "size":{
              "width":42,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58e663b4efee43e5b67c942fae65859e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":670,
                  "y":286},
                "size":{
                  "width":42,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"77f840f2e0af4654bc1adf2f4b78ebac",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":640,
              "y":317},
            "size":{
              "width":170,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25730c4edee24b5bb9bb2313524c9ef9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":640,
                  "y":317},
                "size":{
                  "width":170,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "91fd257011b144dab649173af1b4d7fd":{
      "scriptId":"u0"},
    "66fbcd6b61f744989ea42650d85c9213":{
      "scriptId":"u1"},
    "6d0499fc00b647bab82f19d04e7d0a87":{
      "scriptId":"u2"},
    "7434774c8914411c8c426cf241aa396c":{
      "scriptId":"u3"},
    "480f6403d6734dd7bc32b199f924700b":{
      "scriptId":"u4"},
    "45541f2ef2c540e28bb775f7e9408b29":{
      "scriptId":"u5"},
    "8c507794c7a74f12832fe93fd59eec1f":{
      "scriptId":"u6"},
    "459dc461c4f04c958221129332a5e3c5":{
      "scriptId":"u7"},
    "d80242d9f24045f7912b2fa226aab1ac":{
      "scriptId":"u8"},
    "4ea404f8391c47c3b229c369ced823cc":{
      "scriptId":"u9"},
    "a1e9f2a67e16403fb87b8be4d48bdad8":{
      "scriptId":"u10"},
    "abed30765e3f4277a56db72d03581173":{
      "scriptId":"u11"},
    "3d96607f28ae4018811fcd4d5556d289":{
      "scriptId":"u12"},
    "6063f49ec90448288a89056868fd7e4b":{
      "scriptId":"u13"},
    "ca29fffc5df64bd381b23b8fa7d5bae3":{
      "scriptId":"u14"},
    "e213347119534a5a93efc79cfed03d45":{
      "scriptId":"u15"},
    "0a1b4b62e1bc49ca88b4b2250d5b7e4d":{
      "scriptId":"u16"},
    "03af1254e706447e8185b05be2795222":{
      "scriptId":"u17"},
    "5140c360fc8f4c10bd9623698020e03e":{
      "scriptId":"u18"},
    "806854db1b2f40ca90bcd4396722638d":{
      "scriptId":"u19"},
    "cbb60be409584f67a2ace45720c50e74":{
      "scriptId":"u20"},
    "6d6bdb49d5604fff86f82597c1281b37":{
      "scriptId":"u21"},
    "51c3453d7fca4a8e83e01c1ab94bd24c":{
      "scriptId":"u22"},
    "c61efe91906646618540b537919dd2b4":{
      "scriptId":"u23"},
    "b223fa457ffe4e78b9ed449e9aa9da6c":{
      "scriptId":"u24"},
    "cc6279f579ff41f6b16838efdd3014c6":{
      "scriptId":"u25"},
    "baae714d05ec4575be3ade8626c1ef63":{
      "scriptId":"u26"},
    "9b5a14a320d344949e09c0b4bf12f489":{
      "scriptId":"u27"},
    "bf86bc64d4724386847a745628267ac7":{
      "scriptId":"u28"},
    "20f521266fb44f12bc6e179e8e6d4aee":{
      "scriptId":"u29"},
    "be442ada4b9a44b2a73a5f9ebef6dfc9":{
      "scriptId":"u30"},
    "e13ac42e461a4f8b8600341f4e54dc78":{
      "scriptId":"u31"},
    "2a4507598b594b768a5f1abf286ee9f7":{
      "scriptId":"u32"},
    "cf70fdd5496744d88ec3d2b4b65d723b":{
      "scriptId":"u33"},
    "6954997fe60c4b488efe87ab8e04f62a":{
      "scriptId":"u34"},
    "e04eba76cbe44f33b26c68275083af48":{
      "scriptId":"u35"},
    "09ba5457370e46fab12d6fcb3301f65d":{
      "scriptId":"u36"},
    "e44e4888cf1547ddbfb92460a0b990f5":{
      "scriptId":"u37"},
    "3632370b358a47f88d15eedbc029d9a3":{
      "scriptId":"u38"},
    "f7033c065cbd42d6aabdcfe5f5bf1cb6":{
      "scriptId":"u39"},
    "58e663b4efee43e5b67c942fae65859e":{
      "scriptId":"u40"},
    "77f840f2e0af4654bc1adf2f4b78ebac":{
      "scriptId":"u41"},
    "25730c4edee24b5bb9bb2313524c9ef9":{
      "scriptId":"u42"}}});