$axure.loadCurrentPage({
  "url":"应用推荐.html",
  "generationDate":new Date(1417419973826.8),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"33af87660ade47c799047d0251104625",
    "type":"Axure:Page",
    "name":"应用推荐",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFF333333},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"69eec91c8a11438780daf11a95b7df72",
          "label":"通用底色f0f0f0",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF0F0F0},
            "location":{
              "x":100,
              "y":100},
            "size":{
              "width":320,
              "height":640},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07442505e720438f9f52ca4939f545f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF0F0F0},
                "location":{
                  "x":100,
                  "y":100},
                "size":{
                  "width":320,
                  "height":640},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用推荐/____f0f0f0_u0.png"}},
{
          "id":"6680e8b48c314b7489db152f58df93bf",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":100,
              "y":100},
            "size":{
              "width":320,
              "height":20},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7f574d7f12e4e9992f43954e834ff1b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":100,
                  "y":100},
                "size":{
                  "width":320,
                  "height":20},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/专题列表/u6.jpg"}},
{
          "id":"8b6dcc89471a4259b2ccf9cdaa6ebbb5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "location":{
              "x":100,
              "y":120},
            "size":{
              "width":320,
              "height":44},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":1,
              "blurRadius":2,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40025a1e5030457daa290b63491a6307",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "location":{
                  "x":100,
                  "y":120},
                "size":{
                  "width":320,
                  "height":44},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":1,
                  "blurRadius":2,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用推荐/u4.png"}},
{
          "id":"26e760f40049474eae5282232fd9cc55",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":103,
              "y":127},
            "size":{
              "width":32,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3316f29395b247c3abefef22018eb8dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "location":{
                  "x":103,
                  "y":127},
                "size":{
                  "width":32,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/专题列表/u12.png"}},
{
          "id":"6476fc2d404040f0956788a0f3061ea5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":100.000015258789,
              "y":164},
            "size":{
              "width":320,
              "height":168}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dcab2bc1370047c2ad4c88064a9c7245",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":100.000015258789,
                  "y":164},
                "size":{
                  "width":320,
                  "height":168}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用推荐/u8.png"}},
{
          "id":"5d9606e09dd54dee94933f9228574c41",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":488,
              "y":180},
            "size":{
              "width":105,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5e6a0b906f04d3a82d6e73abc2970d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":488,
                  "y":180},
                "size":{
                  "width":105,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "69eec91c8a11438780daf11a95b7df72":{
      "scriptId":"u0"},
    "07442505e720438f9f52ca4939f545f9":{
      "scriptId":"u1"},
    "6680e8b48c314b7489db152f58df93bf":{
      "scriptId":"u2"},
    "f7f574d7f12e4e9992f43954e834ff1b":{
      "scriptId":"u3"},
    "8b6dcc89471a4259b2ccf9cdaa6ebbb5":{
      "scriptId":"u4"},
    "40025a1e5030457daa290b63491a6307":{
      "scriptId":"u5"},
    "26e760f40049474eae5282232fd9cc55":{
      "scriptId":"u6"},
    "3316f29395b247c3abefef22018eb8dd":{
      "scriptId":"u7"},
    "6476fc2d404040f0956788a0f3061ea5":{
      "scriptId":"u8"},
    "dcab2bc1370047c2ad4c88064a9c7245":{
      "scriptId":"u9"},
    "5d9606e09dd54dee94933f9228574c41":{
      "scriptId":"u10"},
    "c5e6a0b906f04d3a82d6e73abc2970d1":{
      "scriptId":"u11"}}});