$axure.loadCurrentPage({
  "url":"礼包大厅.html",
  "generationDate":new Date(1417419974083.82),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3468754532624f848ae838e959b97b93",
    "type":"Axure:Page",
    "name":"礼包大厅",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFF333333},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d46a90aa4cde477ea899ee76942a8d5f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":71,
              "y":73},
            "size":{
              "width":369,
              "height":167}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c992b71109764509a460ed3826c5a391",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":71,
                  "y":73},
                "size":{
                  "width":369,
                  "height":167}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/礼包大厅/u0.png"}},
{
          "id":"b304a0d5c2534b718c16ebe1723168c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "fill":{
              "fillType":"solid",
              "color":0x660033FF},
            "location":{
              "x":150,
              "y":208},
            "size":{
              "width":210,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6fd5216b91343ad8fcd92cfac65720f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "fill":{
                  "fillType":"solid",
                  "color":0x660033FF},
                "location":{
                  "x":150,
                  "y":208},
                "size":{
                  "width":210,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/礼包大厅/u2.png"}},
{
          "id":"bba191ffda3a4874a401403b58106806",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":160,
              "y":220},
            "size":{
              "width":10,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/首页/u4_end.png",
            "line~":"images/首页/u4_line.png"}},
{
          "id":"da726dadb20d4fd09c3cad6c4e5f9a30",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":149,
              "y":300},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6faa6eeb14c4db69df835f3c2aa18b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":149,
                  "y":300},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "d46a90aa4cde477ea899ee76942a8d5f":{
      "scriptId":"u0"},
    "c992b71109764509a460ed3826c5a391":{
      "scriptId":"u1"},
    "b304a0d5c2534b718c16ebe1723168c7":{
      "scriptId":"u2"},
    "c6fd5216b91343ad8fcd92cfac65720f":{
      "scriptId":"u3"},
    "bba191ffda3a4874a401403b58106806":{
      "scriptId":"u4"},
    "da726dadb20d4fd09c3cad6c4e5f9a30":{
      "scriptId":"u5"},
    "f6faa6eeb14c4db69df835f3c2aa18b9":{
      "scriptId":"u6"}}});